---
sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip
    - .tox

install:
  - pip install -r test-requirements.txt

script:
  - tox -e lint

after_sucess:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/trigger-travis.sh --branch master osism docker-osism-ansible $TRAVIS_ACCESS_TOKEN "new commit in osism-ansible repository"; fi'

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
