---
sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r test-requirements.txt

script:
  - yamllint -c .yamllint.yml playbooks tasks

after_success:
  - test $TRAVIS_PULL_REQUEST = "false" && bash scripts/trigger-travis.sh --branch master osism docker-osism-ansible $TRAVIS_ACCESS_TOKEN "new commit in osism-ansible repository"

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
