---
- name: "[{{ item.port }}] - {{ item.src }} -> {{ item.dest }}"
  wait_for:
    host: "{{ item_in_include }}"
    port: "{{ item.port }}"
    delay: 3
    timeout: 15
  with_items: "{{ groups[item.dest] }}"
  loop_control:
    loop_var: item_in_include
  ignore_errors: true
