---
- name: Prepare docker_registry_external prefix
  set_fact:
    ceph_docker_registry_external: "{{ docker_registry_external }}/"
  when: "image == 'ceph_docker_image'"

- name: Prepare docker_registry_internal prefix
  set_fact:
    ceph_docker_registry_internal: "{{ docker_registry_internal }}/"
  when: "image == 'ceph_docker_image'"

- name: "Pull docker {{ images_external[image] }}"
  docker_image:
    name: "{{ ceph_docker_registry_external|default('') }}{{ images_external[image] }}"
    tag: "{{ images_external[tag] }}"
    state: present

- name: "Tag and push image {{ images_internal[image] }}"
  docker_image:
    name: "{{ ceph_docker_registry_external|default('') }}{{ images_external[image] }}"
    tag: "{{ images_external[tag] }}"
    repository: "{{ ceph_docker_registry_internal|default('') }}{{ images_internal[image] }}"
    push: yes

- name: "Remove local images {{ images_internal[image] }} and {{ images_external[image] }}"
  docker_image:
    name: "{{ item_in_block|regex_replace('index.docker.io/') }}"
    tag: "{{ images_external[tag] }}"
    state: absent
  with_items:
    - "{{ ceph_docker_registry_internal|default('') }}{{ images_internal[image] }}"
    - "{{ ceph_docker_registry_external|default('') }}{{ images_external[image] }}"
  loop_control:
    loop_var: item_in_block
  ignore_errors: true
  when: remove_local_docker_images|default(true)|bool
