---
- name: Get image details
  os_image_facts:
    image: "{{ item.name }}"
    auth: "{{ openstack_environment_service }}"
    validate_certs: no

- name: Download image
  get_url:
    url: "{{ item.url }}"
    dest: "{{ openstack_glance_images_tmpdir }}/{{ item.url|basename }}"
    mode: 0640
    timeout: "{{ item.timeout|default(300) }}"
  when:
    - not openstack_image
    - item.url is defined

- name: Convert image
  command: "qemu-img convert -f qcow2 -O raw {{ openstack_glance_images_tmpdir }}/{{ item.url|basename }} {{ openstack_glance_images_tmpdir }}/{{ item.url|basename }}.raw"
  when:
    - not openstack_image
    - item.url is defined
    - item.format == "qcow2"
    - item.convert_to_raw is defined and item.convert_to_raw|bool

- name: Upload image
  os_image:
    name: "{{ item.name }}"
    container_format: bare
    disk_format: "{% if item.convert_to_raw is defined and item.convert_to_raw|bool %}raw{% else %}{{ item.format }}{% endif %}"
    filename: "{{ openstack_glance_images_tmpdir }}/{% if item.url is defined %}{{ item.url|basename }}{% else %}{{ item.filename }}{% endif %}{% if item.convert_to_raw is defined and item.convert_to_raw|bool %}.raw{% endif %}"
    min_ram: "{{ item.min_ram }}"
    min_disk: "{{ item.min_disk }}"
    is_public: "{{ item.is_public }}"
    properties: "{{ item.properties }}"
    state: present
    auth: "{{ openstack_environment_service }}"
    validate_certs: no
  when: not openstack_image

- name: Remove files
  file:
    path: "{{ item_sub }}"
    state: absent
  with_items:
    - "{{ openstack_glance_images_tmpdir }}/{{ item.url|basename }}"
    - "{{ openstack_glance_images_tmpdir }}/{{ item.url|basename }}.raw"
  loop_control:
    loop_var: item_sub
  when:
    - not openstack_image
    - item.url is defined
