---
- name: Backup mariadb
  hosts: mariadb
  gather_facts: yes

  vars:
    backup_directory: /opt/xtrabackup

  tasks:
  - name: Create required directories
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ operator_user }}"
      group: "{{ operator_group }}"
      mode: 0750
    become: true
    with_items:
      - "{{ backup_directory }}"

  - name: Get status of mariadb container
    command: docker ps -a -f name=/mariadb -f status=running --format "{{ '{{' }}.ID{{ '}}' }}"
    register: result

  - name: Ensure mariadb container is running
    fail:
      msg: mariadb container is not running
    when: result.stdout == ""

  - name: Run innobackupex
    command: docker exec -t mariadb innobackupex /tmp
    async: 60
    poll: 5

  - name: Get latest backup directory
    shell: docker exec -t mariadb find /tmp -name '{{ ansible_date_time.date }}*' | sort | tail -n 1
    register: result

  - name: Set latest backup directory fact
    set_fact:
      backup_directory_latest: "{{ result.stdout }}"

  - name: Ensure backup_directory_latest is not empty
    fail:
      msg: backup_directory_latest is empty
    when: backup_directory_latest == ""

  - name: Extract backup from the container
    command: docker cp mariadb:{{ backup_directory_latest }} /opt/xtrabackup

  - name: Remove backup from the container
    command: docker exec -t mariadb rm -rf {{ backup_directory_latest }}
