---
- name: Manage container
  hosts: all
  serial: "{{ osism_serial['manage_container']|default(osism_serial_default) }}"

  tasks:
    - name: Manage container
      command: "docker {{ container_action }} {{ container_name }}"
