---
- name: Reboot systems
  hosts: all
  become: true
  serial: "{{ osism_serial['reboot']|default('1') }}"

  tasks:
    - name: Reboot system
      shell: sleep 2 && /sbin/shutdown -r now
      async: 1
      poll: 0
