---
- hosts: mirror

  tasks:
  - name: Import gpg key
    command: "docker exec -t aptly_aptly_1 bash -c 'wget -O - {{ aptly_gpg_key }} | gpg --no-default-keyring --keyring trustedkeys.gpg --import'"

  - name: Add repository
    command: "docker exec -t aptly_aptly_1 bash -c 'aptly mirror create -architectures=amd64 node-{{ repository_version }} {{ aptly_repository }}'"

  - name: Update repository
    command: "docker exec -t aptly_aptly_1 bash -c 'aptly mirror update -force=true -skip-existing-packages -max-tries=3 node-{{ repository_version }}'"

  - name: Create snapshot
    command: "docker exec -t aptly_aptly_1 bash -c 'aptly snapshot create node-{{ repository_version }} from mirror node-{{ repository_version }}'"

  # - name: Publish snapshot
  # command: "docker exec -t aptly_aptly_1 bash -c 'aptly publish snapshot -batch=true node-{{ repository_version }} node-{{ repository-version }}'"

  - name: Copy aptly.pub file
    command: "docker exec -t aptly_aptly_1 bash -c 'cp /opt/aptly/aptly.pub /opt/aptly/public/aptly.pub'"
