---
- hosts: localhost
  gather_facts: false
  become: false
  connection: local

  tasks:
  - name: Create aggregates
    os_nova_host_aggregate:
      name: "{{ item.name }}"
      availability_zone: "{{ item.availability_zone }}"
      hosts: "{{ item.hosts }}"
      metadata: "{{ item.metadata }}"
      state: present
      auth: "{{ openstack_environment_service }}"
      validate_certs: no
    with_items: "{{ openstack_nova_aggregates }}"
