---
- hosts: localhost
  gather_facts: false
  become: false
  connection: local

  tasks:
  - name: Create flavors
    os_nova_flavor:
      name: "{{ item.name }}"
      disk: "{{ item.disk }}"
      ephemeral: "{{ item.ephemeral }}"
      flavorid: "{{ item.flavorid }}"
      is_public: "{{ item.is_public }}"
      ram: "{{ item.ram }}"
      swap: "{{ item.swap }}"
      vcpus: "{{ item.vcpus }}"
      state: present
      auth: "{{ openstack_environment_service }}"
      validate_certs: no
    with_items: "{{ openstack_nova_flavors }}"
